# Normalisation

In [1]:
import pandas as pd

In [2]:
lcdi_df = pd.read_csv('lcdi/lcdi_final.csv')
lcdi_df

,country,forest_area,freshwater,paris_agreement,years_since_unfccc,hdi,renewable_energy_consumption,total_greenhouse_gas_emission,region
0,Algeria,0.82,11.2,1.0,31.0,0.745,0.2,2.606857e+05,African Group
1,Angola,53.43,148.0,0.0,24.0,0.591,61.0,7.027561e+04,African Group
2,Benin,27.80,10.3,1.0,30.0,0.504,46.2,1.501766e+04,African Group
3,Botswana,26.92,2.4,1.0,30.0,0.708,27.2,1.216181e+04,African Group
4,Burkina Faso,22.72,12.5,1.0,31.0,0.438,67.5,3.092565e+04,African Group
...,...,...,...,...,...,...,...,...,...
186,Sweden,68.69,171.0,1.0,31.0,0.952,58.4,4.474927e+04,WEOG
187,Switzerland,32.11,40.4,1.0,31.0,0.967,26.4,4.228805e+04,WEOG
188,Turkey,28.87,227.0,0.0,20.0,0.855,13.7,4.959830e+05,WEOG
189,United Kingdom of Great Britain and Northern I...,13.19,145.0,1.0,31.0,0.940,13.5,3.867627e+05,WEOG
190,United States of America,33.87,2818.0,1.0,32.0,0.927,11.2,5.326776e+06,WEOG

Implement min-max normalisation with the formula:
$Xnorm = \frac{X-Xmin}{Xmax-Xmin}$

In [3]:
def min_max_normalise(df, column):
    df[column] = (df[column] - df[column].min()) / (df[column].max() - df[column].min())
    return df

In [4]:

lcdi_df = min_max_normalise(lcdi_df, 'forest_area')
lcdi_df = min_max_normalise(lcdi_df, 'freshwater')
lcdi_df = min_max_normalise(lcdi_df, 'years_since_unfccc')
lcdi_df = min_max_normalise(lcdi_df, 'renewable_energy_consumption')
lcdi_df = min_max_normalise(lcdi_df, 'total_greenhouse_gas_emission')
lcdi_df

,country,forest_area,freshwater,paris_agreement,years_since_unfccc,hdi,renewable_energy_consumption,total_greenhouse_gas_emission,region
0,Algeria,0.008418,0.001978,1.0,0.956522,0.745,0.002079,0.020577,African Group
1,Angola,0.548506,0.026144,0.0,0.652174,0.591,0.634096,0.005546,African Group
2,Benin,0.285392,0.001819,1.0,0.913043,0.504,0.480249,0.001184,African Group
3,Botswana,0.276358,0.000424,1.0,0.913043,0.708,0.282744,0.000959,African Group
4,Burkina Faso,0.233241,0.002208,1.0,0.956522,0.438,0.701663,0.002440,African Group
...,...,...,...,...,...,...,...,...,...
186,Sweden,0.705164,0.030207,1.0,0.956522,0.952,0.607069,0.003531,WEOG
187,Switzerland,0.329638,0.007137,1.0,0.956522,0.967,0.274428,0.003337,WEOG
188,Turkey,0.296376,0.040099,0.0,0.478261,0.855,0.142412,0.039151,WEOG
189,United Kingdom of Great Britain and Northern I...,0.135407,0.025614,1.0,0.956522,0.940,0.140333,0.030529,WEOG
190,United States of America,0.347706,0.497792,1.0,1.000000,0.927,0.116424,0.420493,WEOG

In [5]:
lcdi_df.to_csv("lcdi/lcdi_normalised.csv", index=False)